export interface StudentRequest {
    requestId: string;
    studentId: string; 
    subjectId: string;
    studyType: string; 
    preferredSchedule: string; 
    tuitionFee: string; 
    location: string; 
    description: string; 
    status: string; 
    title: string;
    studentCount: number;
    createdAt: string;
}

export interface StudentRequestCreateRequest {
    id?: string; // Optional for create, will be generated by the server
    studentId: string; 
    subjectId: string;
    studyType: string; 
    preferredSchedule: string; 
    tuitionFee: string; 
    location: string; 
    description: string; 
    status: string; 
    title: string;
    studentCount: number;
    createdAt: string;
}

export interface StudentRequestUpdateRequest {
    studyType?: string; 
    preferredSchedule?: string; 
    tuitionFee?: string; 
    location?: string; 
    description?: string; 
    status?: string; 
    title?: string;
    studentCount?: number;
    createdAt?: string;
}
